### ISSUE TITLE
XPATH doesn't finish running

### ISSUE THREAD

**Issue by NPissarra** [DeltaXML/vscode-xpath-notebook#7]
Hi,

I have instaled the newest versions of XPath and NodeJS on Windows 10. However when I try to run a cell it doesn't finish. Even with a "Hello " || "world"

![Capture](https://user-images.githubusercontent.com/48334581/147796363-49e1eaf5-6057-4749-8cac-41a12d3a1ee3.PNG)

![image](https://user-images.githubusercontent.com/48334581/147796459-52418a63-5254-42d2-81fc-1446a6288b5f.png)

What might be causing this failure?

Regards

Nuno

**Comment by pgfearo** [comment]
On my Windows test machine I have Windows 10 with NodeJS v14.17.4.0. With this setup I can't reproduce your issue, the XPath code cell runs and the result is shown.

Even though you have NodeJS installed it's possible that it's not installed globally. Try running `node --version` from the VS Code terminal window - what does this output?

If it's not a problem with your NodeJS installation then it may be some other extension is conflicting with the XPath Notebook extension in some way. Please try disabling all other extensions using the `Disable all installed extensions` command and then just enabling the XPath Notebook extension to see if the problem still persists.

**Comment by NPissarra** [comment]
Hi pgfearo,

Thanks for your fast answer! 👍 

I was able to find the reason for this failure. I had an older version of NodeJS v11 installed before that was previous the new version v16 in the environment variables. Now XPath is working fine.

Thanks!

Regards

Nuno
